/* Written by MyST v1.8.3 */

#import "myst-imports.typ": *

== Imported Functions

=== Functions Imported by the Chapter. <functions-imported-by-the-chapter>

Chapter One's notebooks import two helper functions:

+ #link("https://patrickjhess.github.io/Imported-Functions/save\_results.html\#save-results-is-a-helper-function-that-asks-users-if-they-wish-to-save-files-created-by-financial-python")[save\_results]: This function helps track files generated by notebooks that are saved.
+ #link("https://patrickjhess.github.io/Imported-Functions/one\_y\_axis.html\#one-y-axis-is-a-helper-function-for-plotting-graphs-created-by-financial-python")[one\_y\_axis]: This function utilizes the matplotlib library to graph multiple series on a single y-axis.

Both functions are part of a module downloaded from DropBox. These and other functions within the #link("https://patrickjhess.github.io/Imported-Functions/intro.html\#functions-imported-by-the-volume-basic-concepts-of-fixed-income")[module] are intended to shift focus from coding to financial concepts.